from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


SIZE_CONTRACTS = {
    "variables": "configuration-only block; declares globals and has no signal ports",
    "bit_source": "out = length values; seed = -1 is random each run",
    "text_source": "out = reference = UTF-8 bits × repeat",
    "text_file_source": "out = reference = file bits × repeat",
    "text_symbol_source": "out = Unicode character symbols × repeat",
    "text_file_symbol_source": "out = UTF-8 file characters × repeat",
    "discrete_symbol_source": "out = length random symbols drawn from configured P(x)",
    "source_analyzer": "symbols, probability and information outputs each match input size",
    "symbols_to_bits": "out = reference = UTF-8 bits of the input symbols",
    "image_file_source": "out = reference = pixel bits",
    "differential_encode": "out = in",
    "differential_decode": "out = in",
    "convolutional_encode": "rate 1/2, K=3, generators (7,5): out = in × 2; reference = in",
    "viterbi_decode": "hard-decision input must be even; out = in / 2",
    "huffman_encode": "reference = in; out is variable-length with a 32-bit size header",
    "huffman_decode": "out must match the size declared by the input header",
    "shannon_fano_encode": "reference = in; out is variable-length with a 32-bit size header",
    "shannon_fano_decode": "out must match the size declared by the input header",
    "symbol_huffman_encode": "reference = input symbols; out is pure Huffman payload by default; optional 32-bit symbol-count header",
    "symbol_huffman_decode": "decodes to the end of the prefix stream; enable header only when the encoder also includes it",
    "symbol_shannon_fano_encode": "reference = input symbols; out is a variable-length bitstream with symbol-count header",
    "symbol_shannon_fano_decode": "out symbols must match the count declared by the bitstream header",
    "rle_encode": "reference = in; out contains complete 9-bit count/value groups",
    "rle_decode": "in must be divisible by 9; out must match the encoded run counts",
    "zip_encode": "reference = in; out contains a 32-bit size header and DEFLATE payload",
    "zip_decode": "out must match the size declared by the input header",
    "hamming74_encode": "in must be divisible by 4; out = in × 7/4; reference = in",
    "hamming74_decode": "in must be divisible by 7; out = in × 4/7",
    "cyclic_encode": "append generator parity to a binary frame; reference = in",
    "cyclic_decode": "remove generator parity from a cyclic codeword",
    "bch_encode": "BCH(15,7) hard block encoder; in must be divisible by 7",
    "bch_decode": "BCH(15,7) nearest-codeword decoder; in must be divisible by 15",
    "reed_solomon_encode": "RS byte-symbol encoder; defaults to RS(15,11)",
    "reed_solomon_decode": "RS byte-symbol decoder; defaults to RS(15,11)",
    "crc_encode": "append configurable CRC checksum bits; reference = in",
    "crc_decode": "remove configurable CRC checksum bits",
    "repetition3_encode": "out = in × 3; reference = in",
    "repetition3_decode": "in must be divisible by 3; out = in / 3",
    "dc_blocker": "first-order DC rejection; out = in",
    "fir_filter": "causal FIR filtering; out = in",
    "normalize_power": "scale to target mean power; out = in",
    "window_function": "multiply by the selected analysis window; out = in",
    "fft": "complex discrete Fourier transform; out = in",
    "ifft": "inverse complex discrete Fourier transform; out = in",
    "fft_shift": "move zero frequency to the center; out = in",
    "bpsk_mod": "out = in",
    "qpsk_mod": "in must be even; out = in / 2 complex symbols",
    "ook_mod": "out = in real-valued on/off symbols",
    "psk8_mod": "in must be divisible by 3; out = in / 3 complex symbols",
    "qam16_mod": "in must be divisible by 4; out = in / 4 complex symbols",
    "fsk2_mod": "orthogonal complex 2-FSK symbols; out = in",
    "awgn": "out = in; seed = -1 is random each run",
    "rayleigh": "out = in; seed = -1 is random each run",
    "rician": "Rician K-factor fading plus AWGN; out = in; seed = -1 is random each run",
    "bpsk_demod": "out = in",
    "qpsk_demod": "out = in × 2 bits",
    "ook_demod": "out = in bits",
    "psk8_demod": "out = in × 3 bits",
    "qam16_demod": "out = in × 4 bits",
    "fsk2_demod": "nearest orthogonal-symbol decision; out = in bits",
    "scope": "in must be a non-empty 1-D signal",
    "constellation": "in must be a non-empty 1-D signal",
    "power_meter": "in must be a non-empty 1-D signal",
    "spectrum_analyzer": "bounded FFT spectrum preview of a non-empty 1-D signal",
    "waterfall_sink": "bounded short-time FFT waterfall preview of a non-empty 1-D signal",
    "evm_meter": "reference and estimate must have identical symbol counts",
    "ber": "reference and estimate must have exactly the same size",
    "ser": "reference and estimate must contain the same number of symbols",
    "python": "Declare PORTS in code for flexible named inputs/outputs; output_size applies to the single default out port",
}


@dataclass(frozen=True)
class BlockSpec:
    type: str
    label: str
    category: str
    description: str
    defaults: dict[str, Any]
    inputs: list[str]
    outputs: list[str]
    gpu_compatible: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {**asdict(self), "size_contract": SIZE_CONTRACTS.get(self.type, "All ports must be non-empty 1-D signals")}


SPECS = [
    BlockSpec("variables", "Variables", "Configuration", "Declare typed global values available to every Python Block.", {"definitions": "symbol_rate = 1_000_000\nrolloff = 0.35\nlabel = 'Experiment A'"}, [], [], True),
    BlockSpec("bit_source", "Bit Source", "Sources", "Generate random binary messages; seed -1 is random each run.", {"length": 4096, "seed": -1}, [], ["out"]),
    BlockSpec("text_source", "Text Source", "Sources", "Convert UTF-8 text into a repeatable bit stream.", {"text": "HELLO", "repeat": 1}, [], ["out", "reference"]),
    BlockSpec("text_file_source", "Text File Source", "Sources", "Load a UTF-8/text file and emit its bytes as bits.", {"file_name": "", "data_base64": "", "repeat": 1}, [], ["out", "reference"], False),
    BlockSpec("text_symbol_source", "Text Symbol Source", "Source theory", "Emit text as visible Unicode character symbols.", {"text": "ABACABAD", "repeat": 1}, [], ["out"], False),
    BlockSpec("text_file_symbol_source", "Text File Symbols", "Source theory", "Load a UTF-8 file and emit visible character symbols.", {"file_name": "", "data_base64": "", "repeat": 1}, [], ["out"], False),
    BlockSpec("discrete_symbol_source", "Discrete Symbol Source", "Source theory", "Generate symbols from a configurable alphabet and probability model.", {"alphabet": "A,B,C,D", "probabilities": "0.5,0.25,0.125,0.125", "length": 100, "seed": -1}, [], ["out"], False),
    BlockSpec("source_analyzer", "Source Information Analyzer", "Source theory", "Measure P(x), self-information, entropy and source efficiency.", {"alphabet": "A,B,C,D", "probabilities": "0.5,0.25,0.125,0.125"}, ["in"], ["symbols", "probability", "information"], False),
    BlockSpec("symbols_to_bits", "Symbols to UTF-8 Bits", "Source theory", "Convert symbol text to a binary UTF-8 stream before channel coding.", {"separator": ""}, ["in"], ["out", "reference"], False),
    BlockSpec("image_file_source", "Image File Source", "Sources", "Load an image and emit grayscale or RGB pixel bits.", {"file_name": "", "data_base64": "", "mode": "grayscale"}, [], ["out", "reference"], False),
    BlockSpec("differential_encode", "Differential Encoder", "Source coding", "Cumulative XOR transform for a binary stream.", {}, ["in"], ["out"]),
    BlockSpec("differential_decode", "Differential Decoder", "Source coding", "Invert a differential binary stream.", {}, ["in"], ["out"]),
    BlockSpec("huffman_encode", "Huffman Encoder", "Source coding", "Pedagogical fixed 2-bit-symbol Huffman encoder.", {"weights": "8,4,2,1"}, ["in"], ["out", "reference"], False),
    BlockSpec("huffman_decode", "Huffman Decoder", "Source coding", "Decode the matching fixed Huffman codebook.", {"weights": "8,4,2,1"}, ["in"], ["out"], False),
    BlockSpec("shannon_fano_encode", "Shannon-Fano Encoder", "Source coding", "Pedagogical Shannon-Fano encoder for 2-bit symbols.", {"weights": "8,4,2,1"}, ["in"], ["out", "reference"], False),
    BlockSpec("shannon_fano_decode", "Shannon-Fano Decoder", "Source coding", "Decode the matching Shannon-Fano codebook.", {"weights": "8,4,2,1"}, ["in"], ["out"], False),
    BlockSpec("symbol_huffman_encode", "Huffman Symbol Encoder", "Source theory", "Huffman-code text symbols using configurable P(x).", {"alphabet": "A,B,C,D", "probabilities": "0.5,0.25,0.125,0.125", "include_header": False}, ["in"], ["out", "reference"], False),
    BlockSpec("symbol_huffman_decode", "Huffman Symbol Decoder", "Source theory", "Recover text symbols with the matching Huffman model.", {"alphabet": "A,B,C,D", "probabilities": "0.5,0.25,0.125,0.125", "include_header": False}, ["in"], ["out"], False),
    BlockSpec("symbol_shannon_fano_encode", "Shannon-Fano Symbol Encoder", "Source theory", "Shannon-Fano-code text symbols using configurable P(x).", {"alphabet": "A,B,C,D", "probabilities": "0.5,0.25,0.125,0.125", "include_header": True}, ["in"], ["out", "reference"], False),
    BlockSpec("symbol_shannon_fano_decode", "Shannon-Fano Symbol Decoder", "Source theory", "Recover text symbols with the matching Shannon-Fano model.", {"alphabet": "A,B,C,D", "probabilities": "0.5,0.25,0.125,0.125", "include_header": True}, ["in"], ["out"], False),
    BlockSpec("rle_encode", "Run-Length Encoder", "Source coding", "Encode binary runs as 8-bit count plus value.", {}, ["in"], ["out", "reference"], False),
    BlockSpec("rle_decode", "Run-Length Decoder", "Source coding", "Decode binary run-length pairs.", {}, ["in"], ["out"], False),
    BlockSpec("zip_encode", "ZIP (DEFLATE) Encoder", "Source coding", "Compress a bitstream with the standard DEFLATE codec.", {}, ["in"], ["out", "reference"], False),
    BlockSpec("zip_decode", "ZIP (DEFLATE) Decoder", "Source coding", "Decompress a bitstream encoded by ZIP Encoder.", {}, ["in"], ["out"], False),
    BlockSpec("hamming74_encode", "Hamming (7,4) Encoder", "Channel coding", "Systematic encoding: [d1 d2 d3 d4 p1 p2 p3].", {}, ["in"], ["out", "reference"]),
    BlockSpec("cyclic_encode", "Cyclic Encoder", "Channel coding", "Polynomial cyclic code with configurable generator.", {"generator": "0b10011"}, ["in"], ["out", "reference"], False),
    BlockSpec("cyclic_decode", "Cyclic Decoder", "Channel coding", "Strip cyclic parity and optionally check syndrome.", {"generator": "0b10011", "check": False}, ["in"], ["out"], False),
    BlockSpec("bch_encode", "BCH (15,7) Encoder", "Channel coding", "Binary BCH block code with two-error correction capability.", {}, ["in"], ["out", "reference"], False),
    BlockSpec("bch_decode", "BCH (15,7) Decoder", "Channel coding", "Nearest-codeword BCH decoder for up to two bit errors.", {}, ["in"], ["out"], False),
    BlockSpec("reed_solomon_encode", "Reed-Solomon Encoder", "Channel coding", "Byte-symbol RS encoder; defaults to RS(15,11).", {"data_symbols": 11, "parity_symbols": 4}, ["in"], ["out", "reference"], False),
    BlockSpec("reed_solomon_decode", "Reed-Solomon Decoder", "Channel coding", "Byte-symbol RS decoder with optional parity check.", {"data_symbols": 11, "parity_symbols": 4, "check": False}, ["in"], ["out"], False),
    BlockSpec("crc_encode", "CRC Encoder", "Channel coding", "Append configurable polynomial CRC bits.", {"width": 8, "polynomial": "0x07", "init": 0}, ["in"], ["out", "reference"], False),
    BlockSpec("crc_decode", "CRC Decoder", "Channel coding", "Remove configurable CRC checksum bits.", {"width": 8}, ["in"], ["out"], False),
    BlockSpec("convolutional_encode", "Convolutional (7,5) Encoder", "Channel coding", "Rate-1/2, K=3 convolutional encoder with generators (7,5).", {}, ["in"], ["out", "reference"], False),
    BlockSpec("viterbi_decode", "Viterbi (7,5) Decoder", "Channel coding", "Hard-decision maximum-likelihood sequence decoder.", {}, ["in"], ["out"], False),
    BlockSpec("repetition3_encode", "Repetition-3 Encoder", "Channel coding", "Repeat each bit three times.", {}, ["in"], ["out", "reference"]),
    BlockSpec("repetition3_decode", "Repetition-3 Decoder", "Channel coding", "Majority decode groups of three bits.", {}, ["in"], ["out"]),
    BlockSpec("dc_blocker", "DC Blocker", "Signal processing", "First-order high-pass DC rejection filter.", {"alpha": 0.995}, ["in"], ["out"], False),
    BlockSpec("fir_filter", "FIR Filter", "Signal processing", "Causal finite impulse response filter with configurable taps.", {"taps": "0.25,0.5,0.25"}, ["in"], ["out"], False),
    BlockSpec("normalize_power", "Normalize Power", "Signal processing", "Scale a signal to the configured mean power.", {"target_power": 1.0}, ["in"], ["out"]),
    BlockSpec("window_function", "Window Function", "Signal processing", "Apply Hann, Hamming, Blackman or rectangular analysis window.", {"window": "hann"}, ["in"], ["out"]),
    BlockSpec("fft", "FFT", "Signal processing", "Compute the complex discrete Fourier transform.", {"normalize": False}, ["in"], ["out"]),
    BlockSpec("ifft", "Inverse FFT", "Signal processing", "Compute the inverse complex discrete Fourier transform.", {"normalize": False}, ["in"], ["out"]),
    BlockSpec("fft_shift", "FFT Shift", "Signal processing", "Move zero frequency to the center of the spectrum.", {}, ["in"], ["out"]),
    BlockSpec("bpsk_mod", "BPSK Modulator", "Modulation", "Map 0 → +1 and 1 → -1.", {}, ["in"], ["out"]),
    BlockSpec("qpsk_mod", "QPSK Modulator", "Modulation", "Gray-free QPSK mapping of bit pairs.", {}, ["in"], ["out"]),
    BlockSpec("ook_mod", "OOK Modulator", "Modulation", "Map bits to off/on amplitudes 0 and 1.", {}, ["in"], ["out"]),
    BlockSpec("psk8_mod", "8-PSK Modulator", "Modulation", "Gray-coded mapping of three-bit groups to eight phases.", {}, ["in"], ["out"]),
    BlockSpec("qam16_mod", "16-QAM Modulator", "Modulation", "Gray-coded four-bit I/Q mapping with unit average symbol energy.", {}, ["in"], ["out"]),
    BlockSpec("fsk2_mod", "2-FSK Symbol Mapper", "Modulation", "Map bits to two orthogonal complex baseband symbols.", {}, ["in"], ["out"]),
    BlockSpec("awgn", "AWGN Channel", "Channels", "Add seeded noise; seed -1 is random each run.", {"ebn0_db": 4.0, "snr_mode": "experiment", "seed": -1}, ["in"], ["out"]),
    BlockSpec("rayleigh", "Rayleigh Fading", "Channels", "Seeded flat fading plus noise; seed -1 is random each run.", {"ebn0_db": 4.0, "snr_mode": "experiment", "seed": -1}, ["in"], ["out"], False),
    BlockSpec("rician", "Rician Fading", "Channels", "Line-of-sight fading with configurable K-factor plus AWGN.", {"k_factor_db": 6.0, "flat": False, "ebn0_db": 4.0, "snr_mode": "experiment", "seed": -1}, ["in"], ["out"]),
    BlockSpec("bpsk_demod", "BPSK Demodulator", "Receivers", "Hard-decision BPSK detector.", {}, ["in"], ["out"]),
    BlockSpec("qpsk_demod", "QPSK Demodulator", "Receivers", "Hard-decision QPSK detector.", {}, ["in"], ["out"]),
    BlockSpec("ook_demod", "OOK Demodulator", "Receivers", "Hard amplitude decision with threshold 0.5.", {}, ["in"], ["out"]),
    BlockSpec("psk8_demod", "8-PSK Demodulator", "Receivers", "Nearest-phase detector for Gray-coded 8-PSK.", {}, ["in"], ["out"]),
    BlockSpec("qam16_demod", "16-QAM Demodulator", "Receivers", "Gray-coded hard-decision 16-QAM detector.", {}, ["in"], ["out"]),
    BlockSpec("fsk2_demod", "2-FSK Detector", "Receivers", "Nearest-symbol hard detector for the orthogonal 2-FSK mapper.", {}, ["in"], ["out"]),
    BlockSpec("hamming74_decode", "Hamming (7,4) Decoder", "Channel coding", "Decode systematic [data parity] words and correct one bit.", {}, ["in"], ["out"]),
    BlockSpec("scope", "Oscilloscope Sink", "Sinks", "Display a time-domain waveform preview and summarize amplitude.", {}, ["in"], []),
    BlockSpec("constellation", "Constellation Sink", "Sinks", "Summarize I/Q samples for constellation inspection.", {}, ["in"], []),
    BlockSpec("power_meter", "Power Meter", "Sinks", "Measure mean signal power.", {}, ["in"], []),
    BlockSpec("spectrum_analyzer", "Spectrum Analyzer", "Sinks", "Display a centered magnitude spectrum in dB.", {"fft_size": 256, "window": "hann"}, ["in"], []),
    BlockSpec("waterfall_sink", "Waterfall Sink", "Sinks", "Display successive short-time spectra as a waterfall heatmap.", {"fft_size": 64, "window": "hann"}, ["in"], []),
    BlockSpec("evm_meter", "EVM Meter", "Sinks", "Measure RMS error vector magnitude against ideal reference symbols.", {}, ["reference", "estimate"], []),
    BlockSpec("ber", "BER Meter", "Sinks", "Compare received bits with a reference stream.", {}, ["reference", "estimate"], []),
    BlockSpec("ser", "Symbol Error Rate", "Source theory", "Compare original and decoded text symbols.", {}, ["reference", "estimate"], [], False),
    BlockSpec("python", "Python Block", "Custom", "Write process(signal, params), or declare PORTS/process_batch for optimized multi-frame processing.", {"gain": 1.0, "output_size": "same", "runtime_executor": "auto", "runtime_batch_size": 0}, ["in"], ["out"], False),
]

SPEC_BY_TYPE = {spec.type: spec for spec in SPECS}
